In [1]:
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
import os
import pandas as pd
import numpy as np

In [2]:
TRAIN_DIR = 'Dataset/train'
TEST_DIR = 'Dataset/test'

In [3]:
def createdataframe(dir):
    image_paths = []
    labels = []
    for label in os.listdir(dir):
        for imagename in os.listdir(os.path.join(dir,label)):
            image_paths.append(os.path.join(dir,label,imagename))
            labels.append(label)
        print(label, "completed")
    return image_paths,labels

In [4]:
train = pd.DataFrame()
train['image'], train['label'] = createdataframe(TRAIN_DIR)

angry completed
disgust completed
fear completed
happy completed
neutral completed
sad completed
surprise completed


In [5]:
print(train)

                                              image     label
0         Dataset/train\angry\Training_10118481.jpg     angry
1         Dataset/train\angry\Training_10120469.jpg     angry
2         Dataset/train\angry\Training_10131352.jpg     angry
3         Dataset/train\angry\Training_10161559.jpg     angry
4          Dataset/train\angry\Training_1021836.jpg     angry
...                                             ...       ...
28704  Dataset/train\surprise\Training_99916297.jpg  surprise
28705  Dataset/train\surprise\Training_99924420.jpg  surprise
28706  Dataset/train\surprise\Training_99937001.jpg  surprise
28707  Dataset/train\surprise\Training_99951755.jpg  surprise
28708  Dataset/train\surprise\Training_99984132.jpg  surprise

[28709 rows x 2 columns]


In [6]:
test = pd.DataFrame()
test['image'], test['label'] = createdataframe(TEST_DIR)

angry completed
disgust completed
fear completed
happy completed
neutral completed
sad completed
surprise completed


In [7]:
print(test)

                                              image     label
0       Dataset/test\angry\PrivateTest_10131363.jpg     angry
1       Dataset/test\angry\PrivateTest_10304478.jpg     angry
2        Dataset/test\angry\PrivateTest_1054527.jpg     angry
3       Dataset/test\angry\PrivateTest_10590091.jpg     angry
4        Dataset/test\angry\PrivateTest_1109992.jpg     angry
...                                             ...       ...
7173  Dataset/test\surprise\PublicTest_98089595.jpg  surprise
7174  Dataset/test\surprise\PublicTest_98567249.jpg  surprise
7175  Dataset/test\surprise\PublicTest_98972870.jpg  surprise
7176  Dataset/test\surprise\PublicTest_99242645.jpg  surprise
7177  Dataset/test\surprise\PublicTest_99446963.jpg  surprise

[7178 rows x 2 columns]


In [8]:
print(test['image'])

0         Dataset/test\angry\PrivateTest_10131363.jpg
1         Dataset/test\angry\PrivateTest_10304478.jpg
2          Dataset/test\angry\PrivateTest_1054527.jpg
3         Dataset/test\angry\PrivateTest_10590091.jpg
4          Dataset/test\angry\PrivateTest_1109992.jpg
                            ...                      
7173    Dataset/test\surprise\PublicTest_98089595.jpg
7174    Dataset/test\surprise\PublicTest_98567249.jpg
7175    Dataset/test\surprise\PublicTest_98972870.jpg
7176    Dataset/test\surprise\PublicTest_99242645.jpg
7177    Dataset/test\surprise\PublicTest_99446963.jpg
Name: image, Length: 7178, dtype: object


In [10]:
from tqdm.notebook import tqdm
def extract_features(images):
    features = []
    for image in tqdm(images):
        img = load_img(image, color_mode="grayscale")
        img = np.array(img)
        features.append(img)
    features = np.array(features)
    features = features.reshape(len(features),48,48,1)
    return features
train_features = extract_features(train['image'])

  0%|          | 0/28709 [00:00<?, ?it/s]

In [11]:
print(train_features)

[[[[ 50]
   [ 32]
   [ 15]
   ...
   [133]
   [151]
   [ 86]]

  [[ 57]
   [ 34]
   [ 22]
   ...
   [138]
   [151]
   [ 89]]

  [[ 61]
   [ 30]
   [ 24]
   ...
   [142]
   [149]
   [ 89]]

  ...

  [[103]
   [100]
   [100]
   ...
   [149]
   [104]
   [ 85]]

  [[107]
   [111]
   [113]
   ...
   [151]
   [120]
   [ 86]]

  [[104]
   [104]
   [112]
   ...
   [143]
   [136]
   [ 83]]]


 [[[ 29]
   [ 24]
   [ 29]
   ...
   [ 11]
   [ 12]
   [ 17]]

  [[ 17]
   [ 14]
   [ 14]
   ...
   [ 15]
   [ 20]
   [ 23]]

  [[  0]
   [  4]
   [  3]
   ...
   [ 33]
   [ 35]
   [ 23]]

  ...

  [[250]
   [248]
   [247]
   ...
   [ 44]
   [ 47]
   [ 43]]

  [[247]
   [248]
   [248]
   ...
   [ 41]
   [ 58]
   [ 55]]

  [[249]
   [248]
   [244]
   ...
   [ 15]
   [ 24]
   [ 24]]]


 [[[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  ...

  [[  0]
   [  0]
   [  0]
   

In [12]:
test_features = extract_features(test['image'])

  0%|          | 0/7178 [00:00<?, ?it/s]

In [13]:
print(test_features)

[[[[ 46]
   [ 34]
   [ 26]
   ...
   [ 10]
   [ 13]
   [ 22]]

  [[ 50]
   [ 28]
   [ 21]
   ...
   [ 11]
   [ 10]
   [ 21]]

  [[ 50]
   [ 27]
   [ 15]
   ...
   [ 22]
   [ 24]
   [ 22]]

  ...

  [[208]
   [179]
   [108]
   ...
   [191]
   [205]
   [204]]

  [[212]
   [198]
   [149]
   ...
   [181]
   [200]
   [204]]

  [[208]
   [201]
   [171]
   ...
   [165]
   [180]
   [189]]]


 [[[ 55]
   [ 33]
   [ 54]
   ...
   [ 40]
   [ 42]
   [ 52]]

  [[ 43]
   [ 42]
   [ 36]
   ...
   [ 62]
   [ 75]
   [ 85]]

  [[ 45]
   [ 54]
   [ 18]
   ...
   [ 84]
   [102]
   [111]]

  ...

  [[242]
   [240]
   [242]
   ...
   [152]
   [177]
   [186]]

  [[244]
   [242]
   [242]
   ...
   [117]
   [183]
   [193]]

  [[245]
   [242]
   [245]
   ...
   [132]
   [163]
   [187]]]


 [[[123]
   [123]
   [126]
   ...
   [ 52]
   [ 46]
   [ 43]]

  [[116]
   [115]
   [116]
   ...
   [ 52]
   [ 49]
   [ 51]]

  [[105]
   [107]
   [109]
   ...
   [ 57]
   [ 57]
   [ 60]]

  ...

  [[ 96]
   [ 98]
   [ 97]
   

In [14]:
x_train = train_features/255.0
x_test = test_features/255.0

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()
le.fit(train['label'])

LabelEncoder()

In [17]:
y_train = le.transform(train['label'])
y_test = le.transform(test['label'])

In [18]:
y_train = to_categorical(y_train,num_classes = 7)
y_test = to_categorical(y_test,num_classes = 7)

In [19]:
from tensorflow.keras.layers import BatchNormalization

model = Sequential()

model.add(Conv2D(64, kernel_size=(3,3), activation='relu', input_shape=(48,48,1)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.5))

model.add(Conv2D(128, kernel_size=(3,3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.5))

model.add(Conv2D(256, kernel_size=(3,3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.5))

model.add(Flatten())
#fully connected layers
model.add(Dense(256, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
#output
model.add(Dense(7, activation='softmax'))

C:\Users\akhan\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [20]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [21]:
model.fit(x_train, y_train,batch_size=64,epochs=100,validation_data=(x_test, y_test))

Epoch 1/100
449/449 ━━━━━━━━━━━━━━━━━━━━ 196s 416ms/step - accuracy: 0.1955 - loss: 2.4452 - val_accuracy: 0.1934 - val_loss: 2.0527
Epoch 2/100
449/449 ━━━━━━━━━━━━━━━━━━━━ 140s 312ms/step - accuracy: 0.3261 - loss: 1.7296 - val_accuracy: 0.3738 - val_loss: 1.5853
Epoch 3/100
449/449 ━━━━━━━━━━━━━━━━━━━━ 141s 315ms/step - accuracy: 0.4025 - loss: 1.5348 - val_accuracy: 0.4021 - val_loss: 1.5249
Epoch 4/100
449/449 ━━━━━━━━━━━━━━━━━━━━ 140s 311ms/step - accuracy: 0.4295 - loss: 1.4713 - val_accuracy: 0.4727 - val_loss: 1.3617
Epoch 5/100
449/449 ━━━━━━━━━━━━━━━━━━━━ 136s 302ms/step - accuracy: 0.4595 - loss: 1.4178 - val_accuracy: 0.4695 - val_loss: 1.3670
Epoch 6/100
449/449 ━━━━━━━━━━━━━━━━━━━━ 136s 303ms/step - accuracy: 0.4752 - loss: 1.3616 - val_accuracy: 0.4615 - val_loss: 1.3716
Epoch 7/100
449/449 ━━━━━━━━━━━━━━━━━━━━ 132s 295ms/step - accuracy: 0.4927 - loss: 1.3270 - val_accuracy: 0.4731 - val_loss: 1.3499
Epoch 8/100
449/449 ━━━━━━━━━━━━━━━━━━━━ 132s 294ms/step - accuracy: 

In [22]:
model_json = model.to_json()
with open("emotiondetector1.json",'w') as json_file:
    json_file.write(model_json)
model.save("emotiondetector1.h5")